apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-server-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-client-sa
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: my-server-svc
  namespace: default
spec:
  selector:
    app: my-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      labels:
        app: my-server
    spec:
      serviceAccountName: my-server-sa
      containers:
      - name: my-server
        image: my-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spiffe-workload-api/spire-agent.sock
        volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-client-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-client
  template:
    metadata:
      labels:
        app: my-client
    spec:
      serviceAccountName: my-client-sa
      restartPolicy: Always
      containers:
      - name: my-client
        image: my-client:latest
        imagePullPolicy: Never
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spiffe-workload-api/spire-agent.sock
        volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
